name: Qing Ping
author: Qing Ping
baseurl: /ChanningPing.github.io
description: Sentiment Analysis | Machine Learning | Information Visualization
github: https://github.com/ChanningPing
twitter: https://twitter.com/gaosuwoniu
facebook: https://www.facebook.com/gaosu.woniu
linkedin: https://www.linkedin.com/in/ping-qing-a64aa387/
email: qp27@drexel.edu
location: 39°57'20"N   75°11'51"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
